// automaticly generated by wsjcpp:v0.2.50

#include <wsjcpp_core.h>

class RES___src_resources_user_0_png_pathfba0ac : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename() const override;
        virtual const std::string &getPackAs() const override;
        virtual int getBufferSize() const override;
        virtual const char *getBuffer() const override;
};


