language: cpp c
sudo: required
branches:
  only:
    - master
            
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      compiler: gcc
      env:
        - WITH_TEST=yes
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"
      install: 
        - cmake --version
        - g++ -v
      script: 
        - cmake . -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux
        - make
        
before_script:
    - |
      if [ "$TRAVIS_OS_NAME" = linux ]; then
        (
          cd $HOME &&
          git clone --depth 1 -b master https://github.com/microsoft/vcpkg.git vcpkg &&
          cd vcpkg &&
          ./bootstrap-vcpkg.sh &&
          ./vcpkg install zlib:x64-linux
          if [ "$WITH_TEST" = "yes" ]; then
            ./vcpkg install gtest:x64-linux
          fi
        )
      fi

notifications:
  email: false
