/**********************************************************************************
 *          Project
 *    __ _
 *   / _| |__   __ _       ___  ___ _ ____   _____ _ __
 *  | |_| '_ \ / _` | ___ / __|/ _ \ '__\ \ / / _ \ '__|
 *  |  _| | | | (_| ||___|\__ \  __/ |   \ V /  __/ |
 *  |_| |_| |_|\__, |     |___/\___|_|    \_/ \___|_|
 *                |_|
 *
 * MIT License
 *
 * Copyright (c) 2011-2025 FreeHackQuest <freehackquest@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 ***********************************************************************************/

// automaticly generated by models.json

#include "model_useful_link_user_favorite.h"

#include <algorithm>
#include <iostream>
#include <wsjcpp_core.h>

ModelUsefulLinkUserFavorite::ModelUsefulLinkUserFavorite() {
  TAG = "ModelUsefulLinkUserFavorite";
  m_nLocalId = 0;
  m_sUsefulLinkUuid = "";
  m_nUsefulLinkId = 0;
  m_sUserUuid = "";
  m_nUserId = 0;
  m_nDateTime = 0;
}

ModelUsefulLinkUserFavorite::~ModelUsefulLinkUserFavorite() {
  //
}

int ModelUsefulLinkUserFavorite::getLocalId() const { return m_nLocalId; }
void ModelUsefulLinkUserFavorite::setLocalId(int nVal) { m_nLocalId = nVal; }

const std::string &ModelUsefulLinkUserFavorite::getUsefulLinkUuid() const { return m_sUsefulLinkUuid; }
void ModelUsefulLinkUserFavorite::setUsefulLinkUuid(const std::string &sVal) {
  m_sUsefulLinkUuid = sVal;
  m_sUsefulLinkUuid_lowercase = WsjcppCore::toLower(sVal);
}
bool ModelUsefulLinkUserFavorite::hasInUsefulLinkUuid_lowercase(const std::string &sVal) {
  return m_sUsefulLinkUuid_lowercase.find(sVal) != std::string::npos;
}

int ModelUsefulLinkUserFavorite::getUsefulLinkId() const { return m_nUsefulLinkId; }
void ModelUsefulLinkUserFavorite::setUsefulLinkId(int nVal) { m_nUsefulLinkId = nVal; }

const std::string &ModelUsefulLinkUserFavorite::getUserUuid() const { return m_sUserUuid; }
void ModelUsefulLinkUserFavorite::setUserUuid(const std::string &sVal) {
  m_sUserUuid = sVal;
  m_sUserUuid_lowercase = WsjcppCore::toLower(sVal);
}
bool ModelUsefulLinkUserFavorite::hasInUserUuid_lowercase(const std::string &sVal) {
  return m_sUserUuid_lowercase.find(sVal) != std::string::npos;
}

int ModelUsefulLinkUserFavorite::getUserId() const { return m_nUserId; }
void ModelUsefulLinkUserFavorite::setUserId(int nVal) { m_nUserId = nVal; }

long ModelUsefulLinkUserFavorite::getDateTime() const { return m_nDateTime; }
void ModelUsefulLinkUserFavorite::setDateTime(long nVal) { m_nDateTime = nVal; }

void ModelUsefulLinkUserFavorite::copy(const ModelUsefulLinkUserFavorite &m) {
  this->setLocalId(m.getLocalId());
  this->setUsefulLinkUuid(m.getUsefulLinkUuid());
  this->setUsefulLinkId(m.getUsefulLinkId());
  this->setUserUuid(m.getUserUuid());
  this->setUserId(m.getUserId());
  this->setDateTime(m.getDateTime());
}

ModelUsefulLinkUserFavorite *ModelUsefulLinkUserFavorite::clone() const {
  ModelUsefulLinkUserFavorite *pModel = new ModelUsefulLinkUserFavorite();
  pModel->copy(*this);
  return pModel;
}

nlohmann::json ModelUsefulLinkUserFavorite::toJson() {
  nlohmann::json jsonRet;
  jsonRet["id"] = m_nLocalId;
  jsonRet["usefullinkuuid"] = m_sUsefulLinkUuid;
  jsonRet["usefullinkid"] = m_nUsefulLinkId;
  jsonRet["useruuid"] = m_sUserUuid;
  jsonRet["userid"] = m_nUserId;
  jsonRet["dt"] = m_nDateTime;
  return jsonRet;
}
