FROM debian:10.0
LABEL "maintainer"="FreeHackQuest Team <freehackquest@gmail.com>"
LABEL "repository"="https://github.com/freehackquest/fhq-server"

WORKDIR /root/

RUN apt-get update && \
    apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_12.x -o setup_node_12x.sh && bash setup_node_12x.sh

# basic libs

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    make cmake \
    g++ \
    pkg-config \
    libcurl4-openssl-dev \
    zlibc zlib1g zlib1g-dev \
    libpng-dev \
    default-libmysqlclient-dev \ 
    libwebsockets-dev \
    apt-utils \
    locales

# install qt5\

RUN apt-get install -y \
    libqt5sql5-mysql \
    libqt5websockets5 \
    libqt5websockets5-dev \
    qt5-default \
    qtchooser

# Fix for building on debian system (mysqlclient library)
# RUN ln -s /usr/lib/x86_64-linux-gnu/pkgconfig/mariadb.pc /usr/lib/x86_64-linux-gnu/pkgconfig/mysqlclient.pc

RUN sed -i -e "s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/" /etc/locale.gen && \
    echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

RUN mkdir -p /usr/share/fhq-server \
    && mkdir -p /usr/share/fhq-server/public/games \
    && mkdir -p /var/log/fhq-server \
    && touch /var/log/fhq-server/error.log

COPY ./scripts/dockerhold.sh /root/dockerhold.sh

WORKDIR /root/

# 1234 - ws
# 4613 - wss
# 7080 - http port (without ssl)
EXPOSE 1234 4613 7080

# todo mount volume
CMD bash /root/dockerhold.sh
